-- Generated by cloudgate/bundle.py: demo categories, products, variants and opening stock.
-- Applied to SANDBOX databases only, after schema.sql.
-- @sample-catalog:start (skipped with apply_sql.py --skip-sample / bundle sample-data.sql)
-- ---------------------------------------------------------------- seed: sample catalogue (dev only)
INSERT INTO categories (Name, Color, SortOrder)
SELECT v.Name, v.Color, v.SortOrder FROM (
  SELECT 'Drinks' AS Name, '#0ea5e9' AS Color, 1 AS SortOrder UNION ALL
  SELECT 'Snacks', '#f59e0b', 2 UNION ALL
  SELECT 'Groceries', '#10b981', 3 UNION ALL
  SELECT 'Household', '#8b5cf6', 4
) v
WHERE NOT EXISTS (SELECT 1 FROM categories);

INSERT INTO products (Name, Sku, Barcode, CategoryId, PriceCents, CostCents, StockQty, LowStockThreshold, Unit, IsWeighed)
SELECT v.Name, v.Sku, v.Barcode, (SELECT Id FROM categories WHERE Name = v.Cat), v.PriceCents, v.CostCents, v.StockQty, 5, v.Unit, v.IsWeighed FROM (
  SELECT 'Sparkling water 500ml' AS Name, 'DR-001' AS Sku, '6001234500017' AS Barcode, 'Drinks' AS Cat, 1499 AS PriceCents, 800 AS CostCents, 48 AS StockQty, 'each' AS Unit, 0 AS IsWeighed UNION ALL
  SELECT 'Cola 330ml can', 'DR-002', '6001234500024', 'Drinks', 1799, 1000, 36, 'each', 0 UNION ALL
  SELECT 'Orange juice 1L', 'DR-003', '6001234500031', 'Drinks', 3499, 2200, 12, 'each', 0 UNION ALL
  SELECT 'Salted peanuts 100g', 'SN-001', '6001234500048', 'Snacks', 2299, 1300, 24, 'each', 0 UNION ALL
  SELECT 'Potato chips 125g', 'SN-002', '6001234500055', 'Snacks', 2499, 1400, 3, 'each', 0 UNION ALL
  SELECT 'Milk chocolate bar', 'SN-003', '6001234500062', 'Snacks', 1899, 1100, 40, 'each', 0 UNION ALL
  SELECT 'Brown bread 700g', 'GR-001', '6001234500079', 'Groceries', 1999, 1200, 10, 'each', 0 UNION ALL
  SELECT 'Full cream milk 2L', 'GR-002', '6001234500086', 'Groceries', 3299, 2400, 15, 'each', 0 UNION ALL
  SELECT 'Bananas', 'GR-003', '2000000000012', 'Groceries', 1999, 1100, 20, 'kg', 1 UNION ALL
  SELECT 'Dishwashing liquid 750ml', 'HH-001', '6001234500093', 'Household', 4599, 2800, 8, 'each', 0
) v
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO inventory_movements (ProductId, Delta, Reason, Reference, Note, CreatedBy)
SELECT p.Id, p.StockQty, 'receive', 'SEED', 'Opening stock', 'system'
FROM products p
WHERE p.StockQty > 0 AND NOT EXISTS (SELECT 1 FROM inventory_movements m WHERE m.ProductId = p.Id AND m.Reference = 'SEED');
