-- Generated by cloudgate/bundle.py from cloudgate/schema.sql (sample catalogue removed).
-- Applied to every database the bundle creates (sandbox and production).
-- Cloudgate POS — SQLite schema (pos_db)
-- Conventions: every table has Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL (Cloudgate rule),
-- PascalCase columns, money as INTEGER minor units (cents) to match the Cloudgate Wallet API,
-- quantities as REAL (weighed goods), booleans as INTEGER 0/1, timestamps as UTC DATETIME text.
-- Safe to re-run: IF NOT EXISTS everywhere, seed rows guarded by NOT EXISTS.

-- ---------------------------------------------------------------- settings
CREATE TABLE IF NOT EXISTS settings (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Key TEXT NOT NULL UNIQUE,
  Value TEXT,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------- catalogue
CREATE TABLE IF NOT EXISTS categories (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Name TEXT NOT NULL,
  Color TEXT,                            -- tile colour on the POS grid (hex)
  SortOrder INTEGER NOT NULL DEFAULT 0,
  IsActive INTEGER NOT NULL DEFAULT 1,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS suppliers (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Name TEXT NOT NULL,
  ContactName TEXT,
  Email TEXT,
  Phone TEXT,
  Notes TEXT,
  IsActive INTEGER NOT NULL DEFAULT 1,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Name TEXT NOT NULL,
  Sku TEXT,
  Barcode TEXT,                          -- primary barcode (EAN/UPC/Code128); extra ones in product_barcodes
  CategoryId INTEGER,
  SupplierId INTEGER,
  PriceCents INTEGER NOT NULL DEFAULT 0, -- selling price incl. tax when prices_include_tax = 1
  CostCents INTEGER,
  TaxRateBp INTEGER,                     -- NULL = store default (settings.tax_rate_bp)
  TaxExempt INTEGER NOT NULL DEFAULT 0,
  TrackInventory INTEGER NOT NULL DEFAULT 1,
  StockQty REAL NOT NULL DEFAULT 0,
  LowStockThreshold REAL,
  Unit TEXT NOT NULL DEFAULT 'each',     -- each | kg | g | l | m
  IsWeighed INTEGER NOT NULL DEFAULT 0,  -- quantity entered/scale, price per unit
  ImageUrl TEXT,
  ImageFileId TEXT,
  Color TEXT,                            -- tile colour override
  Status TEXT NOT NULL DEFAULT 'active', -- active | inactive
  Notes TEXT,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Additional barcodes for the same product (pack sizes, supplier codes).
CREATE TABLE IF NOT EXISTS product_barcodes (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ProductId INTEGER NOT NULL,
  Barcode TEXT NOT NULL,
  Label TEXT,
  PackQty REAL NOT NULL DEFAULT 1,       -- units of the product one scan adds (e.g. 6 for a six-pack)
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Append-only stock ledger; StockQty on the product is the materialised sum.
CREATE TABLE IF NOT EXISTS inventory_movements (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ProductId INTEGER NOT NULL,
  Delta REAL NOT NULL,
  Reason TEXT NOT NULL,                  -- sale | refund | receive | adjust | count | void
  Reference TEXT,
  Note TEXT,
  CreatedBy TEXT,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Goods received (a delivery from a supplier).
CREATE TABLE IF NOT EXISTS stock_receipts (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Reference TEXT NOT NULL,
  SupplierId INTEGER,
  Note TEXT,
  TotalCostCents INTEGER NOT NULL DEFAULT 0,
  CreatedBy TEXT,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_receipt_items (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ReceiptId INTEGER NOT NULL,
  ProductId INTEGER NOT NULL,
  Qty REAL NOT NULL,
  UnitCostCents INTEGER NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------- registers & shifts
CREATE TABLE IF NOT EXISTS registers (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Name TEXT NOT NULL,
  Location TEXT,
  IsActive INTEGER NOT NULL DEFAULT 1,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- A teller's session on a register: opened with a float, closed with a cash count.
CREATE TABLE IF NOT EXISTS shifts (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  RegisterId INTEGER NOT NULL,
  TellerUserId INTEGER NOT NULL,
  TellerName TEXT,
  TellerEmail TEXT,
  Status TEXT NOT NULL DEFAULT 'open',   -- open | closed
  OpeningFloatCents INTEGER NOT NULL DEFAULT 0,
  ExpectedCashCents INTEGER,             -- filled at close: float + cash sales - cash refunds + pay-ins - pay-outs
  CountedCashCents INTEGER,
  DifferenceCents INTEGER,
  Note TEXT,
  OpenedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ClosedAt DATETIME,
  ClosedBy TEXT
);

CREATE TABLE IF NOT EXISTS cash_movements (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ShiftId INTEGER NOT NULL,
  Type TEXT NOT NULL,                    -- payin | payout | drop
  AmountCents INTEGER NOT NULL,
  Note TEXT,
  CreatedBy TEXT,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------- customers
CREATE TABLE IF NOT EXISTS customers (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Name TEXT NOT NULL,
  Email TEXT,
  Phone TEXT,
  Notes TEXT,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------- sales
CREATE TABLE IF NOT EXISTS sales (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Reference TEXT NOT NULL UNIQUE,        -- receipt number, e.g. R-100042
  ShiftId INTEGER,
  RegisterId INTEGER,
  TellerUserId INTEGER,
  TellerName TEXT,
  CustomerId INTEGER,
  CustomerName TEXT,
  CustomerEmail TEXT,
  Status TEXT NOT NULL DEFAULT 'open',   -- open | held | completed | voided | refunded | partially_refunded
  Currency TEXT NOT NULL DEFAULT 'ZAR',
  SubtotalCents INTEGER NOT NULL DEFAULT 0,   -- sum of line totals after line discounts
  DiscountCents INTEGER NOT NULL DEFAULT 0,   -- sale-level discount
  TaxCents INTEGER NOT NULL DEFAULT 0,
  TotalCents INTEGER NOT NULL DEFAULT 0,
  PaidCents INTEGER NOT NULL DEFAULT 0,
  ChangeCents INTEGER NOT NULL DEFAULT 0,
  RefundedCents INTEGER NOT NULL DEFAULT 0,
  HoldLabel TEXT,
  Note TEXT,
  CompletedAt DATETIME,
  VoidedAt DATETIME,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sale_items (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  SaleId INTEGER NOT NULL,
  ProductId INTEGER,
  Name TEXT NOT NULL,
  Sku TEXT,
  Barcode TEXT,
  Unit TEXT NOT NULL DEFAULT 'each',
  Qty REAL NOT NULL DEFAULT 1,
  UnitPriceCents INTEGER NOT NULL DEFAULT 0,
  DiscountCents INTEGER NOT NULL DEFAULT 0, -- per line, absolute
  TaxRateBp INTEGER NOT NULL DEFAULT 0,
  TaxCents INTEGER NOT NULL DEFAULT 0,
  LineTotalCents INTEGER NOT NULL DEFAULT 0, -- qty * unit - discount (incl. tax when tax-inclusive)
  RefundedQty REAL NOT NULL DEFAULT 0,
  Position INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sale_payments (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  SaleId INTEGER NOT NULL,
  Method TEXT NOT NULL,                  -- cash | card (Cloudgate Wallet hosted page)
  AmountCents INTEGER NOT NULL,          -- applied to the sale
  TenderedCents INTEGER,                 -- cash handed over
  ChangeCents INTEGER NOT NULL DEFAULT 0,
  Status TEXT NOT NULL DEFAULT 'succeeded', -- pending | succeeded | failed | expired | refunded
  Reference TEXT,
  ConnectPaymentId INTEGER,
  PaymentUrl TEXT,
  IsProduction INTEGER NOT NULL DEFAULT 0,
  RawJson TEXT,
  CreatedBy TEXT,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refunds (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  SaleId INTEGER NOT NULL,
  Reference TEXT NOT NULL,
  Method TEXT NOT NULL,                  -- cash | card
  AmountCents INTEGER NOT NULL,
  Reason TEXT,
  ItemsJson TEXT,                        -- [{saleItemId, qty, amountCents}]
  ConnectRefundId INTEGER,
  Status TEXT NOT NULL DEFAULT 'completed',
  ShiftId INTEGER,
  CreatedBy TEXT,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sale_events (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  SaleId INTEGER NOT NULL,
  Type TEXT NOT NULL,
  Message TEXT,
  DataJson TEXT,
  CreatedBy TEXT,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------- indexes
CREATE INDEX IF NOT EXISTS ix_products_barcode ON products(Barcode);
CREATE INDEX IF NOT EXISTS ix_products_sku ON products(Sku);
CREATE INDEX IF NOT EXISTS ix_products_category ON products(CategoryId, Status);
CREATE INDEX IF NOT EXISTS ix_product_barcodes_code ON product_barcodes(Barcode);
CREATE INDEX IF NOT EXISTS ix_movements_product ON inventory_movements(ProductId, CreatedAt);
CREATE INDEX IF NOT EXISTS ix_shifts_status ON shifts(Status, RegisterId);
CREATE INDEX IF NOT EXISTS ix_shifts_teller ON shifts(TellerUserId, Status);
CREATE INDEX IF NOT EXISTS ix_sales_status ON sales(Status, CreatedAt);
CREATE INDEX IF NOT EXISTS ix_sales_shift ON sales(ShiftId);
CREATE INDEX IF NOT EXISTS ix_sales_completed ON sales(CompletedAt);
CREATE INDEX IF NOT EXISTS ix_sale_items_sale ON sale_items(SaleId);
CREATE INDEX IF NOT EXISTS ix_sale_payments_sale ON sale_payments(SaleId);
CREATE INDEX IF NOT EXISTS ix_sale_payments_connect ON sale_payments(ConnectPaymentId);
CREATE INDEX IF NOT EXISTS ix_refunds_sale ON refunds(SaleId);
CREATE INDEX IF NOT EXISTS ix_cash_movements_shift ON cash_movements(ShiftId);

-- ---------------------------------------------------------------- seed: settings
INSERT INTO settings (Key, Value)
SELECT v.Key, v.Value FROM (
  SELECT 'store_name' AS Key, 'Cloudgate POS' AS Value UNION ALL
  SELECT 'store_tagline', 'Point of sale' UNION ALL
  SELECT 'store_address', '' UNION ALL
  SELECT 'store_phone', '' UNION ALL
  SELECT 'support_email', '' UNION ALL
  SELECT 'store_url', '' UNION ALL
  SELECT 'store_logo_url', '' UNION ALL
  SELECT 'store_icon_url', '' UNION ALL
  SELECT 'currency', 'ZAR' UNION ALL
  SELECT 'tax_rate_bp', '1500' UNION ALL           -- 15% VAT
  SELECT 'prices_include_tax', '1' UNION ALL
  SELECT 'tax_number', '' UNION ALL
  SELECT 'sale_reference_prefix', 'R-' UNION ALL
  SELECT 'sale_reference_seed', '100000' UNION ALL
  SELECT 'receipt_header', 'Thank you for shopping with us' UNION ALL
  SELECT 'receipt_footer', 'Keep this receipt for returns within 14 days.' UNION ALL
  SELECT 'payment_cash_enabled', '1' UNION ALL
  SELECT 'payment_card_enabled', '1' UNION ALL
  SELECT 'allow_negative_stock', '0' UNION ALL
  SELECT 'require_shift', '1' UNION ALL
  SELECT 'low_stock_threshold', '5' UNION ALL
  SELECT 'quick_cash_amounts', '20,50,100,200' UNION ALL
  SELECT 'label_size', '50x30' UNION ALL
  SELECT 'theme_primary', '#0f172a' UNION ALL
  SELECT 'theme_secondary', '#2563eb'
) v
WHERE NOT EXISTS (SELECT 1 FROM settings s WHERE s.Key = v.Key);

INSERT INTO registers (Name, Location)
SELECT 'Till 1', 'Front counter' WHERE NOT EXISTS (SELECT 1 FROM registers);

-- @sample-catalog:end
