import React,{useEffect,useState} from 'react';
import {auth} from './services/auth';
import './cloudgate-smtp.css';
const preview=import.meta.env.MODE==='preview';

async function request(action,body={}) {
 const base=String(import.meta.env.VITE_IDP_API_URL||import.meta.env.VITE_IDP_BASE_URL||'').replace(/\/$/,'');
 const run=()=>fetch(`${base}/api/idp/${encodeURIComponent(auth.tenancyName)}/admin/email-settings/${action}`,{method:'POST',headers:{'Content-Type':'application/json',...auth.authHeader()},body:JSON.stringify(body)});
 let response=await run();if(response.status===401&&await auth.refresh())response=await run();
 let raw;try{raw=await response.json();}catch{raw=null;}
 if(!response.ok)throw new Error(raw?.error?.message||raw?.message||(typeof raw==='string'?raw:response.status===404?'SMTP settings APIs are not deployed on this Cloudgate server yet.':'Unable to manage SMTP settings. An active tenant Admin account is required.'));
 return raw?.result??raw;
}
export function SmtpSettings(){
 const [value,setValue]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[removing,setRemoving]=useState(false);
 const load=async()=>{setBusy(true);setError('');try{setValue({...await request('details'),smtpPassword:'',clearPassword:false});}catch(e){setError(e.message);}finally{setBusy(false);}};
 useEffect(()=>{if(!preview)load();},[]);
 const change=(key,v)=>setValue(old=>({...old,[key]:v}));
 const save=async(action)=>{setBusy(true);setError('');setNotice('');try{setValue({...await request(action,action==='delete'?{}:value),smtpPassword:'',clearPassword:false});setNotice(action==='delete'?'Custom SMTP removed. App emails use Cloudgate delivery.':'Cloudgate SMTP settings saved.');setRemoving(false);}catch(e){setError(e.message);}finally{setBusy(false);}};
 if(preview)return <section className="cloudgate-smtp panel card"><h2>Email delivery</h2><p>Connect to Cloudgate and sign in as a tenant administrator to configure email delivery. The local preview does not send email.</p></section>;
 return <section className="cloudgate-smtp panel card" onKeyDown={e=>{if(e.key==='Enter'&&e.target.tagName==='INPUT')e.preventDefault();}}><h2>Email delivery</h2><p>Cloudgate sends your app emails by default — no SMTP setup is needed. Only enable custom SMTP if you want to use your own email server. These settings apply to all apps in this tenant, in sandbox and production.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}{!value?<button type="button" disabled={busy} onClick={load}>{busy?'Loading…':'Retry loading settings'}</button>:<><div className="notice" role="status"><strong>{value.smtpEnabled ? 'Delivery: your custom SMTP server' : 'Delivery: Cloudgate (default)'}</strong><p>{value.smtpEnabled ? 'App emails will use the SMTP server configured below. Turn off custom SMTP to return to Cloudgate delivery.' : 'Cloudgate handles email delivery using its configured email server. Leave custom SMTP off to keep using this service.'}</p></div><label><input type="checkbox" checked={value.smtpEnabled} onChange={e=>change('smtpEnabled',e.target.checked)}/> Use my own SMTP server instead</label><div className="form-grid">{[['SMTP host','smtpHost'],['Port','smtpPort'],['Username','smtpUserName'],['Domain','smtpDomain'],['From email','fromAddress'],['Sender name','fromDisplayName']].map(([label,key])=><label key={key}>{label}<input value={value[key]??''} type={key==='smtpPort'?'number':'text'} min={1} max={65535} onChange={e=>change(key,key==='smtpPort'?Number(e.target.value):e.target.value)}/></label>)}<label>Password<input type="password" autoComplete="new-password" value={value.smtpPassword} placeholder={value.hasPassword?'Saved — leave blank to keep':'Not configured'} onChange={e=>change('smtpPassword',e.target.value)}/></label></div><label><input type="checkbox" checked={value.smtpEnableSsl} onChange={e=>change('smtpEnableSsl',e.target.checked)}/> Use TLS</label><label><input type="checkbox" checked={value.smtpUseDefaultCredentials} onChange={e=>change('smtpUseDefaultCredentials',e.target.checked)}/> Skip explicit username/password authentication</label><label><input type="checkbox" checked={value.clearPassword} onChange={e=>change('clearPassword',e.target.checked)}/> Clear saved password</label><div className="actions"><button type="button" className="button btn-primary" disabled={busy} onClick={()=>save('update')}>Save email settings</button><button type="button" disabled={busy} onClick={()=>setRemoving(true)}>Remove custom SMTP</button></div>{removing&&<div role="alert"><p>Remove the saved SMTP credentials for every app in this tenant? Delivery will revert to Cloudgate’s default server.</p><button type="button" disabled={busy} onClick={()=>save('delete')}>Confirm removal</button><button type="button" onClick={()=>setRemoving(false)}>Cancel</button></div>}</>}</section>;
}
