PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS settings(Id INTEGER PRIMARY KEY AUTOINCREMENT,key TEXT UNIQUE NOT NULL,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS entities(Id INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL,ref TEXT UNIQUE NOT NULL,owner TEXT NOT NULL DEFAULT '',version INTEGER NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)));
CREATE INDEX IF NOT EXISTS events_kind ON entities(kind,Id);
CREATE INDEX IF NOT EXISTS events_owner ON entities(owner,kind);
CREATE TABLE IF NOT EXISTS write_guard(Id INTEGER PRIMARY KEY AUTOINCREMENT,expected TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS events_revision BEFORE INSERT ON write_guard BEGIN SELECT RAISE(ABORT,'The events changed. Refresh and try again.') WHERE NEW.expected<>(SELECT value FROM settings WHERE key='_revision'); END;
INSERT OR IGNORE INTO settings(key,value) VALUES('_revision','0');
INSERT OR IGNORE INTO settings(key,value) VALUES('name','Cloudgate Events');
INSERT OR IGNORE INTO settings(key,value) VALUES('app_name','');
INSERT OR IGNORE INTO settings(key,value) VALUES('app_short_name','Events');
INSERT OR IGNORE INTO settings(key,value) VALUES('tagline','Good things happen together.');
INSERT OR IGNORE INTO settings(key,value) VALUES('description','Find your next unforgettable experience. Live music, ideas, culture and community.');
INSERT OR IGNORE INTO settings(key,value) VALUES('email','');
INSERT OR IGNORE INTO settings(key,value) VALUES('phone','');
INSERT OR IGNORE INTO settings(key,value) VALUES('address','');
INSERT OR IGNORE INTO settings(key,value) VALUES('website_url','');
INSERT OR IGNORE INTO settings(key,value) VALUES('currency','USD');
INSERT OR IGNORE INTO settings(key,value) VALUES('timezone','UTC');
INSERT OR IGNORE INTO settings(key,value) VALUES('theme_primary','#d6be91');
INSERT OR IGNORE INTO settings(key,value) VALUES('theme_accent','#9eab90');
INSERT OR IGNORE INTO settings(key,value) VALUES('theme_background','#171916');
INSERT OR IGNORE INTO settings(key,value) VALUES('logo_url','');
INSERT OR IGNORE INTO settings(key,value) VALUES('icon_url','');
INSERT OR IGNORE INTO settings(key,value) VALUES('favicon_url','');
INSERT OR IGNORE INTO settings(key,value) VALUES('logo_show_name','1');
INSERT OR IGNORE INTO settings(key,value) VALUES('hero_title','Be there. Feel everything.');
INSERT OR IGNORE INTO settings(key,value) VALUES('hero_subtitle','A good night. A new perspective. A room full of your people. Discover events worth showing up for.');
INSERT OR IGNORE INTO settings(key,value) VALUES('hero_image_url','');
INSERT OR IGNORE INTO settings(key,value) VALUES('about_image_url','');
