import React, { useEffect, useState } from 'react';
import { call, localDay } from './api';
import { Field, ErrorBox, Empty } from './ui';

export function SlotPicker({catalog,ids,staffId,setStaffId,slot,setSlot,exclude,token}) {
 const [day,setDay]=useState(localDay(1,catalog.settings.timezone)),[slots,setSlots]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setLoading(true);setError('');setSlot(null);call('availability',{service_ids:ids,date:day,staff_id:staffId,...(exclude?{reference:exclude,token}:{})}).then(r=>{if(alive)setSlots(r.slots);}).catch(e=>alive&&setError(e)).finally(()=>alive&&setLoading(false));return()=>{alive=false;};},[ids.join(','),day,staffId,exclude,token]);
 const people=catalog.staff.filter(p=>ids.every(id=>p.service_ids.includes(id)));
 return <><Field label="Team member"><select value={staffId} onChange={e=>setStaffId(Number(e.target.value))}><option value={0}>Anyone available · first available</option>{people.map(p=><option key={p.Id} value={p.Id}>{p.name} · {p.title}</option>)}</select></Field>{!people.length&&<ErrorBox error="No single team member offers this combination. Please book these services separately."/>}<div className="date-picker"><Field label="Choose a day"><input type="date" value={day} min={localDay(0,catalog.settings.timezone)} max={localDay(Number(catalog.settings.horizon_days),catalog.settings.timezone)} onChange={e=>e.target.value&&setDay(e.target.value)}/></Field><span className="muted">All times in {catalog.settings.timezone.replace('_',' ')}</span></div><div className="days-strip">{Array.from({length:7},(_,i)=>localDay(i,catalog.settings.timezone)).map(d=><button key={d} className={day===d?'selected':''} onClick={()=>setDay(d)}><small>{new Date(d+'T12:00:00').toLocaleDateString('en',{weekday:'short'})}</small><strong>{d.slice(-2)}</strong></button>)}</div><ErrorBox error={error}/>{loading?<p className="loading-inline">Finding a little space…</p>:slots.length?<div className="slots">{slots.map(s=><button key={s.starts+'-'+s.staff_id} className={slot?.starts===s.starts&&slot?.staff_id===s.staff_id?'selected':''} onClick={()=>setSlot(s)}><strong>{s.label}</strong><small>{s.staff_name.split(' ')[0]}</small></button>)}</div>:<Empty title="A full day, or a day of rest.">Try another date or team member. You can also join the waitlist from our service catalog.</Empty>}</>;
}
