-- Generated by cloudgate/bundle.py: demo categories, products, variants and opening stock.
-- Applied to SANDBOX databases only, after schema.sql.
-- @sample-catalog:start (skipped with apply_sql.py --skip-sample, e.g. for production)
-- ---------------------------------------------------------------- seed: sample catalog (dev only, guarded)
INSERT INTO categories (Name, Slug, Description, SortOrder)
SELECT v.Name, v.Slug, v.Description, v.SortOrder FROM (
  SELECT 'Apparel' AS Name, 'apparel' AS Slug, 'T-shirts, hoodies and caps.' AS Description, 1 AS SortOrder UNION ALL
  SELECT 'Accessories', 'accessories', 'Bags, bottles and everyday carry.', 2 UNION ALL
  SELECT 'Home', 'home', 'Mugs, prints and desk gear.', 3
) v
WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.Slug = v.Slug);

INSERT INTO products (Name, Slug, Sku, Brand, ShortDescription, Description, CategoryId, Status, PriceCents, CompareAtCents, HasVariants, IsFeatured, Tags)
SELECT v.Name, v.Slug, v.Sku, v.Brand, v.Short, v.Description,
       (SELECT Id FROM categories c WHERE c.Slug = v.CategorySlug),
       'active', v.PriceCents, v.CompareAtCents, v.HasVariants, v.IsFeatured, v.Tags FROM (
  SELECT 'Classic Tee' AS Name, 'classic-tee' AS Slug, 'TEE-CLASSIC' AS Sku, 'Cloudgate' AS Brand,
         'Heavyweight cotton tee with a relaxed fit.' AS Short,
         'A 220gsm combed-cotton tee that holds its shape wash after wash. Pre-shrunk, side-seamed, printed in Cape Town.' AS Description,
         'apparel' AS CategorySlug, 34900 AS PriceCents, 39900 AS CompareAtCents, 1 AS HasVariants, 1 AS IsFeatured, 'cotton,tee,unisex' AS Tags UNION ALL
  SELECT 'Everyday Hoodie', 'everyday-hoodie', 'HOOD-EVERYDAY', 'Cloudgate',
         'Brushed fleece hoodie with a kangaroo pocket.',
         'Mid-weight 350gsm fleece, double-lined hood, ribbed cuffs and hem. Runs true to size.',
         'apparel', 79900, NULL, 1, 1, 'fleece,hoodie,unisex' UNION ALL
  SELECT 'Insulated Bottle 750ml', 'insulated-bottle-750', 'BTL-750', 'Cloudgate',
         'Keeps drinks cold for 24 hours, hot for 12.',
         'Double-wall stainless steel, powder-coated finish, leak-proof bamboo lid. Fits standard cup holders.',
         'accessories', 44900, NULL, 1, 0, 'bottle,steel' UNION ALL
  SELECT 'Canvas Tote', 'canvas-tote', 'TOTE-CANVAS', 'Cloudgate',
         '12oz canvas tote with an interior pocket.',
         'Reinforced handles rated to 15kg, natural canvas, screen-printed logo.',
         'accessories', 24900, NULL, 0, 0, 'bag,canvas' UNION ALL
  SELECT 'Ceramic Mug', 'ceramic-mug', 'MUG-CERAMIC', 'Cloudgate',
         '350ml stoneware mug, dishwasher safe.',
         'Hand-glazed stoneware with a matte exterior and gloss interior.',
         'home', 18900, 21900, 1, 0, 'mug,ceramic' UNION ALL
  SELECT 'Desk Mat', 'desk-mat', 'MAT-DESK', 'Cloudgate',
         'Vegan leather desk mat, 80 x 40cm.',
         'Water-resistant surface, anti-slip base, stitched edges.',
         'home', 39900, NULL, 0, 1, 'desk,mat'
) v
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.Slug = v.Slug);

-- Option axes for variant products
INSERT INTO product_options (ProductId, Name, Position)
SELECT p.Id, v.Name, v.Position FROM (
  SELECT 'classic-tee' AS Slug, 'Size' AS Name, 0 AS Position UNION ALL
  SELECT 'classic-tee', 'Colour', 1 UNION ALL
  SELECT 'everyday-hoodie', 'Size', 0 UNION ALL
  SELECT 'insulated-bottle-750', 'Colour', 0 UNION ALL
  SELECT 'ceramic-mug', 'Colour', 0
) v JOIN products p ON p.Slug = v.Slug
WHERE NOT EXISTS (SELECT 1 FROM product_options o WHERE o.ProductId = p.Id AND o.Name = v.Name);

INSERT INTO product_option_values (OptionId, Value, Position)
SELECT o.Id, v.Value, v.Position FROM (
  SELECT 'classic-tee' AS Slug, 'Size' AS OptionName, 'S' AS Value, 0 AS Position UNION ALL
  SELECT 'classic-tee', 'Size', 'M', 1 UNION ALL
  SELECT 'classic-tee', 'Size', 'L', 2 UNION ALL
  SELECT 'classic-tee', 'Colour', 'Black', 0 UNION ALL
  SELECT 'classic-tee', 'Colour', 'White', 1 UNION ALL
  SELECT 'everyday-hoodie', 'Size', 'S', 0 UNION ALL
  SELECT 'everyday-hoodie', 'Size', 'M', 1 UNION ALL
  SELECT 'everyday-hoodie', 'Size', 'L', 2 UNION ALL
  SELECT 'everyday-hoodie', 'Size', 'XL', 3 UNION ALL
  SELECT 'insulated-bottle-750', 'Colour', 'Slate', 0 UNION ALL
  SELECT 'insulated-bottle-750', 'Colour', 'Sand', 1 UNION ALL
  SELECT 'ceramic-mug', 'Colour', 'Charcoal', 0 UNION ALL
  SELECT 'ceramic-mug', 'Colour', 'Cream', 1
) v
JOIN products p ON p.Slug = v.Slug
JOIN product_options o ON o.ProductId = p.Id AND o.Name = v.OptionName
WHERE NOT EXISTS (SELECT 1 FROM product_option_values pv WHERE pv.OptionId = o.Id AND pv.Value = v.Value);

-- Variants (stock lives here). Single-variant products get one default row.
INSERT INTO product_variants (ProductId, Sku, Title, OptionsJson, PriceCents, StockQty, IsDefault, Position)
SELECT p.Id, v.Sku, v.Title, v.OptionsJson, v.PriceCents, v.StockQty, v.IsDefault, v.Position FROM (
  SELECT 'classic-tee' AS Slug, 'TEE-CLASSIC-S-BLK' AS Sku, 'S / Black' AS Title, '{"Size":"S","Colour":"Black"}' AS OptionsJson, NULL AS PriceCents, 12 AS StockQty, 1 AS IsDefault, 0 AS Position UNION ALL
  SELECT 'classic-tee', 'TEE-CLASSIC-M-BLK', 'M / Black', '{"Size":"M","Colour":"Black"}', NULL, 20, 0, 1 UNION ALL
  SELECT 'classic-tee', 'TEE-CLASSIC-L-BLK', 'L / Black', '{"Size":"L","Colour":"Black"}', NULL, 8, 0, 2 UNION ALL
  SELECT 'classic-tee', 'TEE-CLASSIC-S-WHT', 'S / White', '{"Size":"S","Colour":"White"}', NULL, 10, 0, 3 UNION ALL
  SELECT 'classic-tee', 'TEE-CLASSIC-M-WHT', 'M / White', '{"Size":"M","Colour":"White"}', NULL, 0, 0, 4 UNION ALL
  SELECT 'classic-tee', 'TEE-CLASSIC-L-WHT', 'L / White', '{"Size":"L","Colour":"White"}', NULL, 4, 0, 5 UNION ALL
  SELECT 'everyday-hoodie', 'HOOD-EVERYDAY-S', 'S', '{"Size":"S"}', NULL, 6, 1, 0 UNION ALL
  SELECT 'everyday-hoodie', 'HOOD-EVERYDAY-M', 'M', '{"Size":"M"}', NULL, 9, 0, 1 UNION ALL
  SELECT 'everyday-hoodie', 'HOOD-EVERYDAY-L', 'L', '{"Size":"L"}', NULL, 3, 0, 2 UNION ALL
  SELECT 'everyday-hoodie', 'HOOD-EVERYDAY-XL', 'XL', '{"Size":"XL"}', 84900, 2, 0, 3 UNION ALL
  SELECT 'insulated-bottle-750', 'BTL-750-SLATE', 'Slate', '{"Colour":"Slate"}', NULL, 25, 1, 0 UNION ALL
  SELECT 'insulated-bottle-750', 'BTL-750-SAND', 'Sand', '{"Colour":"Sand"}', NULL, 14, 0, 1 UNION ALL
  SELECT 'canvas-tote', 'TOTE-CANVAS', 'Default', NULL, NULL, 40, 1, 0 UNION ALL
  SELECT 'ceramic-mug', 'MUG-CERAMIC-CHAR', 'Charcoal', '{"Colour":"Charcoal"}', NULL, 30, 1, 0 UNION ALL
  SELECT 'ceramic-mug', 'MUG-CERAMIC-CREAM', 'Cream', '{"Colour":"Cream"}', NULL, 18, 0, 1 UNION ALL
  SELECT 'desk-mat', 'MAT-DESK', 'Default', NULL, NULL, 11, 1, 0
) v JOIN products p ON p.Slug = v.Slug
WHERE NOT EXISTS (SELECT 1 FROM product_variants pv WHERE pv.Sku = v.Sku);

-- Opening stock movements so the ledger reconciles with StockQty
INSERT INTO inventory_movements (VariantId, ProductId, Delta, Reason, Reference, Note, CreatedBy)
SELECT pv.Id, pv.ProductId, pv.StockQty, 'receive', 'SEED', 'Opening stock', 'system'
FROM product_variants pv
WHERE pv.StockQty > 0
  AND NOT EXISTS (SELECT 1 FROM inventory_movements m WHERE m.VariantId = pv.Id AND m.Reference = 'SEED');

