import json
from engine import Engine,q,encoded

def seed_sql():
    e=Engine({'settings':[], 'entities':[]},{'Id':'1','Role':'Admin','IsActive':True},now=1789430400)
    for index,(title,category,summary,price,color) in enumerate([
        ('Design thinking, made practical','Design','Turn a messy challenge into a clear, useful solution.',0,'#d9ecab'),
        ('The confident project leader','Business','Bring people, priorities and delivery into focus.',4900,'#eac7ae'),
        ('Your first data story','Technology','Find the insight in a spreadsheet and make it matter.',7900,'#c8c4e8')]):
        c=e.dispatch(dict(op='course-save',title=title,summary=summary,description=summary+' This practical course takes you from foundational ideas to a repeatable approach. Work through short lessons, apply what you learn and check your understanding with a final assessment.',category=category,level='Beginner',price=price,currency='USD',instructor=['Alex Morgan','Sam Patel','Taylor Chen'][index],instructors=['3'],image_url='/course-'+str(index+1)+'.svg'))
        topics=[('A useful starting point','Foundations','Start by writing down one problem you want to solve. Make it specific: who is affected, what happens, and why does it matter?\n\nA clear problem statement makes the next decision easier. Avoid jumping straight to solutions. Describe the current situation and the outcome you want.\n\nTry it: Write a one-sentence problem statement for a real situation in your work.'),('Ask better questions','Foundations','Good questions create room for learning. Use open questions that invite examples, rather than questions that ask people to confirm your assumptions.\n\nAsk: Tell me about the last time this happened. What did you try? What made it difficult?\n\nPractice: Rewrite three yes/no questions as open questions.'),('Make a small experiment','In practice','Choose a small, reversible experiment. Define what you expect to learn, the simplest way to test it, and a clear signal of success.\n\nKeep your first test small enough to complete in a day. Capture what you observed separately from what you think it means.\n\nPractice: Draft a simple test plan with a hypothesis, an action and a measurable result.'),('Reflect and improve','In practice','Review your evidence before deciding what to do next. What surprised you? Which assumptions were supported? Which need another test?\n\nShare a concise learning summary with your team: what we tried, what happened, and what we recommend next.\n\nYour final activity: Create a one-page plan that applies the course ideas to a project you care about.')]
        for i,(name,module,body) in enumerate(topics):e.dispatch(dict(op='lesson-save',course=c['ref'],title=name,module=module,position=i,type='article',body=body,minutes=8+i*2,preview=i==0,required=True))
        e.dispatch(dict(op='lesson-save',course=c['ref'],title='Check your understanding',module='Put it together',position=4,type='quiz',minutes=10,required=True,pass_percent=75,max_attempts=3,questions=[{'prompt':'What should you do before choosing a solution?','choices':['Define the problem and desired outcome','Build the largest possible project','Skip research'],'answer':0},{'prompt':'Which question encourages learning?','choices':['Do you agree with my plan?','Tell me about the last time this happened.','Is this good?'],'answer':1},{'prompt':'What makes a useful first experiment?','choices':['It tests every possible scenario','It is expensive and permanent','It is small, measurable and reversible'],'answer':2},{'prompt':'What should you do after a test?','choices':['Review evidence and decide the next step','Ignore unexpected results','Repeat without changing anything'],'answer':0}]))
        e.dispatch(dict(op='course-publish',ref=c['ref'],version=c['version']))
    e.dispatch(dict(op='instructor-save',name='Alex Morgan',user_id='3',bio='Practical learning, thoughtful questions and progress you can see.',active=True))
    return '\n'.join('INSERT OR IGNORE INTO entities(kind,ref,owner,version,data) VALUES('+','.join([q(r['kind']),q(r['ref']),q(r['owner']),str(r['version']),q(encoded(r))])+');' for r in e.rows)
