import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const out=new URL('../test-results/',import.meta.url);await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3010/');await page.getByRole('heading',{name:'Your next project, in good hands.'}).waitFor();await page.screenshot({path:new URL('public.png',out).pathname.replace(/^\/([A-Z]:)/,'$1'),fullPage:true});
await page.getByRole('button',{name:'Office',exact:true}).click();await page.getByRole('heading',{name:'A clear view of your day.'}).waitFor();await page.screenshot({path:new URL('office.png',out).pathname.replace(/^\/([A-Z]:)/,'$1'),fullPage:true});
for(const name of ['Requests','Quotes','Jobs','Schedule','Customers','Invoices & payments','Recurring work','Reports','Services','Team','Media library','Settings','My profile']){await page.locator('.sidebar nav').getByRole('button',{name:new RegExp('^'+name.replace('&','\\&'))}).click();await page.locator('.workspace-main h1').first().waitFor();assert.equal(await page.locator('.error').count(),0,'Error on '+name);}
const title='Browser test '+Date.now();
await page.getByRole('button',{name:'Customer',exact:true}).click();await page.goto('http://127.0.0.1:3010/request');await page.getByLabel('Phone number',{exact:true}).fill('0825550100');await page.getByLabel('What do you need help with?').fill(title);await page.getByLabel('Service address',{exact:true}).fill('24 Test Street, Sandbox');await page.getByRole('button',{name:'Send request',exact:true}).click();await page.waitForURL('**/account');
await page.getByRole('button',{name:'Office',exact:true}).click();await page.locator('.sidebar nav').getByRole('button',{name:/^Requests/}).click();await page.getByRole('button',{name:new RegExp(title)}).click();await page.getByRole('button',{name:'Create quote',exact:true}).click();await page.getByRole('dialog').getByLabel('Description',{exact:true}).fill('Replace kitchen mixer');await page.getByRole('dialog').getByLabel('Unit price',{exact:true}).fill('950');await page.getByRole('button',{name:'Save draft quote'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.locator('.sidebar nav').getByRole('button',{name:'Quotes',exact:true}).click();await page.getByRole('button',{name:new RegExp(title)}).click();await page.getByRole('button',{name:'Send quote',exact:true}).click();await page.getByText('Saved successfully.',{exact:true}).waitFor();
await page.getByRole('button',{name:'Customer',exact:true}).click();await page.locator('.portal-tabs').getByRole('button',{name:'Quotes',exact:true}).click();await page.getByRole('button',{name:new RegExp(title)}).click();await page.getByRole('button',{name:'Review & approve'}).click();await page.getByRole('button',{name:'Approve quote & create job'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.locator('.portal-tabs').getByRole('button',{name:'Jobs',exact:true}).click();await page.getByRole('button',{name:new RegExp(title)}).click();await page.getByRole('button',{name:'Pay securely'}).click();await page.getByRole('button',{name:'Confirm simulated payment'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.error').count(),0);
await page.getByRole('button',{name:'Office',exact:true}).click();await page.locator('.sidebar nav').getByRole('button',{name:'Jobs',exact:true}).click();await page.getByRole('button',{name:new RegExp(title)}).click();await page.getByRole('button',{name:'Schedule visit',exact:true}).click();const start=new Date(Date.now()+86400000*60+Math.floor(Math.random()*100000000));const end=new Date(start.getTime()+3600000);const local=d=>new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);await page.getByLabel('Start',{exact:true}).fill(local(start));await page.getByLabel('End',{exact:true}).fill(local(end));await page.getByLabel('Maya Daniels',{exact:true}).check();await page.getByRole('button',{name:'Save visit'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'Start visit',exact:true}).click();await page.getByRole('button',{name:'Complete visit',exact:true}).click();await page.getByRole('button',{name:'Complete job',exact:true}).click();await page.getByRole('button',{name:'Issue final invoice',exact:true}).click();await page.getByRole('button',{name:'Download PDF'}).waitFor();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download PDF'}).click();const pdf=await downloadPromise;await pdf.saveAs(new URL('invoice.pdf',out).pathname.replace(/^\/([A-Z]:)/,'$1'));assert.equal(await page.locator('.error').count(),0);
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:3010/');await page.getByRole('heading',{name:'Your next project, in good hands.'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Public overflow');await page.screenshot({path:new URL('public-mobile.png',out).pathname.replace(/^\/([A-Z]:)/,'$1'),fullPage:true});
await page.getByRole('button',{name:'Office',exact:true}).click();await page.getByRole('heading',{name:'A clear view of your day.'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Office overflow');await page.screenshot({path:new URL('office-mobile.png',out).pathname.replace(/^\/([A-Z]:)/,'$1'),fullPage:true});
assert.deepEqual(errors,[]);await browser.close();console.log('Browser checks passed: public, all office routes, quote approval, simulated deposit, mobile overflow.');
