import{chromium}from'playwright';import assert from'node:assert/strict';import fs from'node:fs/promises';
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1280,height:900}});await page.goto('http://127.0.0.1:3010/');await page.getByRole('button',{name:'Office',exact:true}).click();await page.getByRole('heading',{name:'A clear view of your day.'}).waitFor();
const api=async(op,data={},role='admin',route='jobs')=>{const response=await page.request.post('http://127.0.0.1:3010/api/'+route,{headers:{'X-Jobs-Preview':'1','X-Preview-Role':role},data:{...data,op}});const value=await response.json();return {status:response.status(),value};};
const original=(await api('workspace')).value.settings;
const image=await page.locator('.metric').first().screenshot();const upload=await api('upload',{content:image.toString('base64'),name:'test-logo.png',path:'jobs/branding'},'admin','branding-media');assert.equal(upload.status,200);
assert.equal((await api('settings',{values:{theme_primary:'#254f78',theme_accent:'#d7b655',logo_url:upload.value.url}})).status,200);await page.reload();await page.getByRole('heading',{name:'A clear view of your day.'}).waitFor();assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--green').trim()),'#254f78');assert.equal(await page.locator('.sidebar .brand-logo').getAttribute('src'),upload.value.url);assert.equal((await api('delete',{id:upload.value.id},'admin','branding-media')).status,400);
const request=(await api('request-create',{title:'Private photo QA',address:'Test location',request_key:crypto.randomUUID()},'customer','requests')).value;const attachment=await api('attachment-add',{entity:request.ref,content:image.toString('base64'),name:'work.png'},'customer','attachments');assert.equal(attachment.status,200);assert.equal((await api('attachment-read',{ref:attachment.value.ref},'other','attachments')).status,400);assert.equal((await api('attachment-read',{ref:attachment.value.ref},'customer','attachments')).value.content,image.toString('base64'));
await api('settings',{values:{theme_primary:original.theme_primary,theme_accent:original.theme_accent,logo_url:original.logo_url}});assert.equal((await api('delete',{id:upload.value.id},'admin','branding-media')).status,200);await page.reload();await page.getByRole('heading',{name:'A clear view of your day.'}).waitFor();
await page.locator('.sidebar nav').getByRole('button',{name:'Media library',exact:true}).click();await page.getByRole('heading',{name:'Your business, in pictures.'}).waitFor();assert.equal(await page.locator('.error').count(),0);await page.screenshot({path:'test-results/media.png',fullPage:true});await browser.close();console.log('Media and theme checks passed: save/reload, logo, deletion guard, private photo isolation.');
