import React,{useEffect,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowUpRight,Search,X,LogOut,House} from 'lucide-react';
import {Brand} from './ui';
import {PoweredByCloudgate} from '../shared/CloudgateAbout';

export default function BackOfficeNav({pages,labels,icons,page,go,identity,role,logout,drawer,setDrawer,requestCount}) {
 const [query,setQuery]=useState('');
 useEffect(()=>{if(!drawer)setQuery('');},[drawer]);
 const groups=[['Workspace',['overview','requests','quotes','jobs','calendar','customers','invoices','recurring','reports']],['Business',['services','team']],['Administration',['media','email','users','logs','analytics','settings','about']]];
 const content=<><div className="office-nav-brand"><Brand/><button type="button" className="mobile-close icon-button" aria-label="Close navigation" onClick={()=>setDrawer(false)}><X size={18}/></button></div><label className="office-nav-search"><Search size={15}/><input aria-label="Find a back office section" placeholder="Find a section…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" aria-label="Clear navigation search" onClick={()=>setQuery('')}><X size={14}/></button>}</label><nav aria-label="Back office">{groups.map(([title,items])=>{const shown=items.filter(p=>pages.includes(p)&&labels[p].toLowerCase().includes(query.trim().toLowerCase()));return shown.length>0&&<React.Fragment key={title}><span className="sidebar-label">{title}</span>{shown.map(p=>{const Icon=icons[p];return <button type="button" key={p} className={page===p?'active':''} aria-current={page===p?'page':undefined} onClick={()=>{setQuery('');go(p);}}><Icon size={17}/><span>{labels[p]}</span>{p==='requests'&&requestCount>0&&<span className="nav-count">{requestCount}</span>}</button>;})}</React.Fragment>;})}{!pages.some(p=>p!=='profile'&&labels[p].toLowerCase().includes(query.trim().toLowerCase()))&&<p className="muted">No sections found.</p>}</nav><div className="office-nav-footer"><PoweredByCloudgate className="office-powered" onOpen={()=>{setQuery('');go('about');}}/><a className="office-public-link" href="/" target="_blank" rel="noreferrer"><House size={19}/><span><strong>Open website</strong><small>View as a customer</small></span><ArrowUpRight size={16}/></a><div className="office-user-card"><button type="button" className="office-profile" onClick={()=>go('profile')} aria-current={page==='profile'?'page':undefined}><span className="avatar">{(identity.name||'User').split(' ').map(n=>n[0]).join('').slice(0,2)}</span><span><strong>{identity.name||'My account'}</strong><small>{role} · My profile</small></span></button><button type="button" className="office-logout" onClick={logout}><LogOut size={14}/>Sign out</button></div></div></>;
 return <><aside className="sidebar office-sidebar">{content}</aside><Dialog.Root open={drawer} onOpenChange={setDrawer}><Dialog.Portal><Dialog.Overlay className="office-drawer-overlay"/><Dialog.Content className="sidebar office-drawer"><Dialog.Title className="office-sr-only">Back office navigation</Dialog.Title><Dialog.Description className="office-sr-only">Choose a workspace or administration section.</Dialog.Description>{content}</Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
