import React, { useEffect, useRef, useState } from 'react';
import { Plus, RefreshCw, Search } from 'lucide-react';
import { adminUsersRequest as request } from './admin-users';
import { preview } from './api';
import { Button, ErrorBox, Field, Modal, Badge } from './ui';

const blank = { email: '', name: '', surname: '', phoneNumber: '', password: '' };
const protectedAccount = user => ['admin', 'administrator', 'owner'].includes(String(user?.role || '').toLowerCase());
export default function UserManagement() {
  const [filter,setFilter]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0),[revision,setRevision]=useState(0);
  const [data,setData]=useState({items:[],totalCount:0}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [error,setError]=useState(''),[formError,setFormError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState(null),[confirm,setConfirm]=useState(null);
  const mutation=useRef(false);
  useEffect(()=>{let active=true;if(preview){setLoading(false);return;}setLoading(true);setError('');
    request('list',{skip:page*25,take:25,filter:query}).then(result=>{if(!Array.isArray(result?.items))throw new Error('User management is unavailable on this Cloudgate server.');if(active)setData(result);}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));
    return()=>{active=false;};
  },[query,page,revision]);
  const run=async(operation)=>{if(mutation.current)return;mutation.current=true;setBusy(true);setFormError('');try{await operation();}catch(e){setFormError(e.message);}finally{mutation.current=false;setBusy(false);}};
  const edit=user=>run(async()=>{setError('');const result=await request('details',{id:user.id});setForm({...result,password:''});});
  const save=e=>{e.preventDefault();run(async()=>{const payload={email:form.email.trim(),name:form.name,surname:form.surname,phoneNumber:form.phoneNumber};if(form.id)payload.id=form.id;else payload.password=form.password;const result=await request(form.id?'update':'create',payload);if(!result?.id)throw new Error('Unable to verify the saved account. Refresh before retrying.');setForm(null);setNotice('User saved.');setRevision(v=>v+1);});};
  const act=()=>run(async()=>{const {user,action}=confirm;const result=await request(action,{id:user.id,...(action==='set-active'?{isActive:!user.isActive}:{})});if(action==='delete'?!result?.deleted:action==='request-password-reset'?result?.success!==true:!result?.id)throw new Error('Unable to verify the result. Refresh before retrying.');setConfirm(null);setNotice(action==='request-password-reset'?'Password reset email requested.':'User updated.');setRevision(v=>v+1);});
  if(preview)return <section className="panel"><h2>Cloudgate user management</h2><p>Connect to Cloudgate and sign in as a tenant administrator to search, create and manage app users. Preview does not change accounts or send email.</p></section>;
  return <section className="panel users-module"><p className="muted">Manage Cloudgate app identities for this tenant. Team members and job assignments are managed separately under Team.</p><div className="panel-heading"><form className="actions" onSubmit={e=>{e.preventDefault();setPage(0);setQuery(filter);}}><label className="search"><Search size={16}/><input aria-label="Search app users" placeholder="Name, email or phone" value={filter} onChange={e=>setFilter(e.target.value)}/></label><Button secondary busy={loading}>Search</Button></form><div className="actions"><Button secondary disabled={loading||busy} onClick={()=>setRevision(v=>v+1)} aria-label="Refresh users"><RefreshCw size={16}/></Button><Button disabled={busy} onClick={()=>{setForm({...blank});setFormError('');}}><Plus size={16}/>Add user</Button></div></div><ErrorBox error={error||(!form&&!confirm?formError:'')}/>{notice&&<p className="notice" role="status">{notice}</p>}{loading?<p role="status">Loading users…</p>:<div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.items.map(user=><tr key={user.id}><td><strong>{[user.name,user.surname].filter(Boolean).join(' ')||user.email}</strong><div>{user.email}</div><small>ID: {user.id}</small></td><td>{user.role}</td><td><Badge>{user.isActive?'active':'disabled'}</Badge></td><td><div className="actions"><Button secondary disabled={busy} onClick={()=>edit(user)}>{protectedAccount(user)?'View':'Edit'}</Button>{!protectedAccount(user)&&<select aria-label={'Actions for '+user.email} value="" disabled={busy} onChange={e=>{if(e.target.value){setFormError('');setConfirm({user,action:e.target.value});}}}><option value="">More actions…</option><option value="set-active">{user.isActive?'Disable user':'Enable user'}</option><option value="request-password-reset" disabled={!user.isActive}>Send password reset</option><option value="delete">Delete user</option></select>}</div></td></tr>)}</tbody></table>{!data.items.length&&<p>No users found.</p>}</div>}<div className="spread"><span className="muted">{data.totalCount} users · Page {page+1}</span><div className="actions"><Button secondary disabled={!page||loading||busy} onClick={()=>setPage(p=>p-1)}>Previous</Button><Button secondary disabled={(page+1)*25>=data.totalCount||loading||busy} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div>
  {form&&<Modal title={form.id?'User details':'Create user'} close={()=>!busy&&setForm(null)}><form onSubmit={save}><ErrorBox error={formError}/>{[['Email','email','email',256],['First name','name','text',64],['Surname','surname','text',64],['Phone number','phoneNumber','tel',32],...(!form.id?[['Initial password','password','password',128]]:[])].map(([label,key,type,max])=><Field key={key} label={label}><input type={type} maxLength={max} minLength={key==='password'?8:undefined} required={['email','password'].includes(key)} autoComplete={key==='password'?'new-password':undefined} disabled={busy||protectedAccount(form)} value={form[key]||''} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))}/></Field>)}{protectedAccount(form)?<p>Administrator accounts are managed in Cloudgate.</p>:<Button busy={busy}>Save user</Button>}</form></Modal>}
  {confirm&&<Modal title={confirm.action==='delete'?'Delete user?':confirm.action==='request-password-reset'?'Send password reset?':confirm.user.isActive?'Disable user?':'Enable user?'} close={()=>!busy&&setConfirm(null)}><p>{confirm.user.email}</p><p>{confirm.action==='delete'?'This removes the app identity. Existing Jobs business records are retained.':confirm.action==='request-password-reset'?'Send a secure reset link by email. The password stays unchanged until the user completes the reset.':confirm.user.isActive?'This user will no longer be able to sign in.':'This user will be able to sign in again.'}</p><ErrorBox error={formError}/><div className="actions"><Button secondary disabled={busy} onClick={()=>setConfirm(null)}>Cancel</Button><Button busy={busy} onClick={act}>{confirm.action==='request-password-reset'?'Send reset email':'Confirm'}</Button></div></Modal>}
  </section>;
}
