#!/usr/bin/env python3
"""Package the shop's backend for the App Store: `.template/workflow-template.json` (the controller
exported as a template bundle) plus `.template/schema.sql` and `.template/sample-data.sql` split
out of `cloudgate/schema.sql` at the `@sample-catalog` markers.

    python cloudgate/bundle.py            # export + split
    python cloudgate/bundle.py --sql-only # only regenerate the two SQL files

The export uses the Cloudgate MCP tool `export_controller_bundle` (workflow group) with the same
cached token deploy.py uses. Re-run after every `cloudgate:deploy` so the bundle matches what is
published on the tenant.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from deploy import Mcp  # noqa: E402

ROOT = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(ROOT)
OUT = os.path.join(APP, '.template')


def split_schema():
    sql = open(os.path.join(ROOT, 'schema.sql'), encoding='utf-8').read()
    start, end = sql.find('-- @sample-catalog:start'), sql.find('-- @sample-catalog:end')
    if start < 0 or end < start:
        raise SystemExit('schema.sql is missing the @sample-catalog markers')
    schema = sql[:start] + sql[end:]
    sample = sql[start:end]
    os.makedirs(OUT, exist_ok=True)
    open(os.path.join(OUT, 'schema.sql'), 'w', encoding='utf-8', newline='\n').write(
        '-- Generated by cloudgate/bundle.py from cloudgate/schema.sql (sample catalogue removed).\n'
        '-- Applied to every database the bundle creates (sandbox and production).\n' + schema)
    open(os.path.join(OUT, 'sample-data.sql'), 'w', encoding='utf-8', newline='\n').write(
        '-- Generated by cloudgate/bundle.py: demo categories, products, variants and opening stock.\n'
        '-- Applied to SANDBOX databases only, after schema.sql.\n' + sample)
    print('wrote .template/schema.sql and .template/sample-data.sql')


def export_bundle():
    config = json.load(open(os.path.join(ROOT, 'deploy.config.json'), encoding='utf-8'))
    mcp = Mcp.from_env()
    res = mcp.call('export_controller_bundle', {'project_id': config['projectId']})
    text = res if isinstance(res, str) else json.dumps(res)
    bundle = json.loads(text) if isinstance(text, str) else text
    if isinstance(bundle, str):
        bundle = json.loads(bundle)
    projects = bundle.get('Projects') or bundle.get('projects') or []
    if not projects:
        raise SystemExit('export returned no projects: ' + text[:300])
    # Keep the bundle free of tenant-specific secrets: channel passwords are rotated on import,
    # and the App Store creates its own API key. Strip static keys' values defensively.
    for project in projects:
        template = project.get('Template') or project.get('template') or {}
        for ws in template.get('WebSockets') or []:
            ws['Password'] = ''
        for key in template.get('Keys') or []:
            if key.get('Type') in (2,):  # StaticEncrypted
                key['Value'] = ''
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, 'workflow-template.json')
    open(path, 'w', encoding='utf-8', newline='\n').write(json.dumps(bundle, indent=2) + '\n')
    endpoints = sum(len((p.get('Template') or {}).get('Endpoints') or []) for p in projects)
    databases = sum(len((p.get('Template') or {}).get('Databases') or []) for p in projects)
    print(f'wrote .template/workflow-template.json: {len(projects)} project(s), {endpoints} endpoints, {databases} databases')


if __name__ == '__main__':
    split_schema()
    if '--sql-only' not in sys.argv:
        export_bundle()
