CREATE TABLE IF NOT EXISTS customer_accounts (Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id TEXT UNIQUE NOT NULL, name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', created INTEGER NOT NULL, updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS booking_accounts (Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, booking_ref TEXT UNIQUE NOT NULL REFERENCES bookings(reference), user_id TEXT NOT NULL, created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS booking_account_user ON booking_accounts(user_id);
