import React,{useEffect,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import '@fontsource/dm-sans/400.css';import '@fontsource/dm-sans/500.css';import '@fontsource/dm-sans/600.css';import '@fontsource/dm-sans/700.css';import '@fontsource/instrument-serif/400.css';import '@fontsource/instrument-serif/400-italic.css';
import{ArrowUpRight,ArrowRight,Ticket,CalendarDays,MapPin,Search,Plus,Menu,RefreshCw,Users,ScanLine,BarChart3,Settings,ImageIcon,Mail,Activity,Info,Receipt,ClipboardList,UserRound,Check,Download,Camera,X,Clock}from'lucide-react';
import{auth}from'../shared/services/auth';import{call,preview,previewRole,money,dateLabel,csv}from'./api';import{Brand,Button,Field,ErrorBox,Empty,Badge,Modal}from'./ui';import{publishBranding,useDocumentBranding}from'./branding';
import BackOfficeNav from './BackOfficeNav';import BrandingEditor,{Asset}from'./BrandingEditor';import MediaPanel from './MediaPanel';import UserManagement from './UserManagement';import{SmtpSettings}from'./smtp-settings';import{MyProfile,useSelfProfile}from'./profile';import{CloudgateWorkflowLogs}from'../shared/CloudgateWorkflowLogs';import{CloudgateAbout,AppVersion}from'../shared/CloudgateAbout';
import {brandSettings} from './branding-model';
import Storefront,{OfficeOverview,eventArtwork} from './Storefront';
import './branding.css';import './style.css';import './back-office.css';import './events.css';import './premium.css';

const adminPath=location.pathname.startsWith('/admin'),accountPath=location.pathname.startsWith('/account');
const labels={overview:'Overview',events:'Events',orders:'Bookings',attendees:'Attendees',checkin:'Check-in',waitlist:'Waitlist',reports:'Reports',staff:'Event staff',refunds:'Refunds',media:'Files & media',email:'Email delivery',users:'User management',logs:'Logs',settings:'Settings',about:'About',profile:'My profile'};
const icons={overview:BarChart3,events:CalendarDays,orders:Receipt,attendees:Ticket,checkin:ScanLine,waitlist:ClipboardList,reports:BarChart3,staff:Users,refunds:Receipt,media:ImageIcon,email:Mail,users:Users,logs:Activity,settings:Settings,about:Info,profile:UserRound};
const fields=e=>Object.fromEntries(new FormData(e.currentTarget));
const inputDate=n=>{const d=new Date(n*1000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const when=n=>new Date(n*1000).toLocaleDateString('en',{month:'short',day:'numeric'});

function Table({rows,columns}){return rows.length?<div className="table-scroll"><table><thead><tr>{columns.map(([h])=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.ref||i}>{columns.map(([h,render])=><td key={h}>{render(r)}</td>)}</tr>)}</tbody></table></div>:<Empty title="Nothing here yet">Your records will appear here as people book and your team gets to work.</Empty>;}
function App(){
 const [catalog,setCatalog]=useState(null),[data,setData]=useState(null),[session,setSession]=useState(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(null),[page,setPage]=useState(location.hash.slice(1)||'overview'),[drawer,setDrawer]=useState(false),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[selected,setSelected]=useState('');
 useDocumentBranding(adminPath);const profile=useSelfProfile(!!session&&!preview),signed=preview?!!previewRole():!!session,admin=['admin','administrator','owner'].includes(data?.role),staff=admin||data?.role==='staff',settings=data?.settings||catalog?.settings||{},rows=k=>(data?.records||[]).filter(r=>r.kind===k),events=rows('event');
 const load=async()=>{const c=await call('catalog');setCatalog(c);publishBranding(c.settings);if(preview?!!previewRole():!!auth.getAccessToken()){const d=await call('workspace');setData(d);publishBranding(d.settings);return d;}};
 useEffect(()=>{(async()=>{try{if(!preview)setSession(await auth.init());await load();const payment=new URLSearchParams(location.search).get('payment');if(payment){const r=await call('status',{ref:payment},false,'payment-status');await load();setNotice(r.status==='succeeded'?'Payment confirmed. Your tickets are ready.':r.status==='review'?'Your booking needs organiser review.':'Payment is awaiting confirmation.');history.replaceState(null,'','/account');}}catch(e){setError(e.message);}finally{setReady(true);}})();},[]);
 useEffect(()=>{const f=()=>{setPage(location.hash.slice(1)||'overview');setSearch('');};window.addEventListener('hashchange',f);return()=>window.removeEventListener('hashchange',f);},[]);
 const go=p=>{location.hash=p;setPage(p);setDrawer(false);setSearch('');};
 const login=(role='attendee')=>{if(preview){sessionStorage.setItem('events.preview.role',role);location.href=role==='attendee'?'/account':'/admin';return;}const callback=new URL(import.meta.env.VITE_IDP_RETURN_URL||location.origin);callback.pathname=adminPath?'/admin':'/account';callback.search='';callback.hash='';location.assign(auth.loginUrl(callback.href));};
 const logout=async()=>{if(preview)sessionStorage.removeItem('events.preview.role');else await auth.logout();location.href='/';};
 const execute=async(op,values={},route,close=true)=>{setBusy(true);setError('');setNotice('');try{const r=await call(op,values,false,route);await load();if(close)setModal(null);setNotice('Saved successfully.');return r;}catch(e){setError(e.message);throw e;}finally{setBusy(false);}};
 const act=(...args)=>execute(...args).catch(()=>{});
 const checkout=async o=>{try{const r=await execute('checkout',{ref:o.ref},'checkout',false);if(r.simulated)setModal({type:'payment',record:o});else location.assign(r.payment_url);}catch{}};
 const filtered=list=>list.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));
 const alerts=<><ErrorBox error={error}/>{notice&&<div className="notice" role="status"><Check size={16}/>{notice}</div>}</>;
 if(!ready)return <main className="loading"><Ticket size={40}/><h2>Finding your next good thing…</h2></main>;
 if(!catalog)return <main className="login-card"><h1>Let’s reconnect.</h1>{alerts}<Button onClick={()=>location.reload()}>Try again</Button></main>;
 const header=<header className="event-header"><Brand/><nav><a href="/#discover">Discover events</a><a href="/#why">The experience</a>{signed&&<a href="/account">My tickets</a>}</nav><div className="actions">{signed&&staff&&<a className="text-link" href="/admin"><ArrowUpRight size={15}/>Back office</a>}<button className="text-link" onClick={signed?logout:()=>login()}>{signed?'Sign out':'Sign in'}</button></div></header>;
 const footer=<footer className="event-footer"><Brand/><p>{settings.description}</p><div>{signed&&staff&&<a href="/admin">Back office <ArrowUpRight size={14}/></a>}<small>Powered by Cloudgate <AppVersion/></small></div></footer>;
 let content;
 if(adminPath){
 const pages=admin?Object.keys(labels):['overview','events','attendees','checkin','profile'];
 const event=events.find(e=>e.ref===selected),orders=rows('order'),tickets=rows('ticket');
 const filterBar=<label className="search"><Search size={17}/><input aria-label="Search records" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records…"/></label>;
 if(page==='overview')content=<OfficeOverview allowedPages={pages} events={events} tickets={tickets} orders={orders} go={go} renderTable={list=><Table rows={list} columns={[["Event",r=><span className="schedule-event"><img src={eventArtwork(r)} alt=""/><span>{r.title}<small>{r.venue}</small></span></span>],["When",r=>dateLabel(r.starts)],["Status",r=><Badge>{r.status}</Badge>]]}/>}/>;
 if(page==='events')content=event?<><div className="actions section-gap"><button className="text-link" onClick={()=>setSelected('')}>← All events</button>{admin&&<Button secondary onClick={()=>setModal({type:'event',record:event})}>Edit event</Button>}{admin&&event.status!=='cancelled'&&<Button onClick={()=>act('event-publish',{ref:event.ref,version:event.version})}>Publish event</Button>}{admin&&event.status==='published'&&<Button secondary onClick={()=>act('event-archive',{ref:event.ref,version:event.version})}>Unlist</Button>}{admin&&event.status!=='cancelled'&&<Button secondary onClick={()=>setModal({type:'cancel',record:event})}>Cancel event</Button>}</div><section className="panel"><span className="eyebrow">{event.category}</span><h2>{event.title}</h2><p>{dateLabel(event.starts)} · {event.venue}</p><p>{event.summary}</p><Badge>{event.status}</Badge></section><section className="panel"><div className="panel-heading"><h2>Ticket tiers</h2>{admin&&<Button onClick={()=>setModal({type:'tier',event})}><Plus size={16}/>Add tier</Button>}</div><Table rows={rows('tier').filter(t=>t.event===event.ref)} columns={[["Tier",r=>r.name],["Price",r=>money(r.price,event.currency)],["Capacity",r=>r.capacity],["Sales",r=>r.active?'Active':'Paused'],["",r=>admin&&<button className="text-link" onClick={()=>setModal({type:'tier',event,record:r})}>Edit</button>]]}/></section></>:<>{filterBar}<div className="event-admin-grid">{filtered(events).map(e=><button className="event-admin-card" key={e.ref} onClick={()=>setSelected(e.ref)}><img src={eventArtwork(e)} alt=""/><div><Badge>{e.status}</Badge><h3>{e.title}</h3><p>{dateLabel(e.starts)}</p><span>{e.venue} · {e.capacity} capacity</span></div><ArrowUpRight size={20}/></button>)}</div>{!events.length&&<Empty title="Your first event starts here">Create an event, add ticket tiers, then publish it.</Empty>}</>;
 if(page==='orders')content=<>{filterBar}<section className="panel"><Table rows={filtered(orders).sort((a,b)=>b.created-a.created)} columns={[["Booking",r=><><strong>{r.ref}</strong><small>{r.title}</small></>],["Customer",r=><>{r.name}<small>{r.email}</small></>],["Tickets",r=>r.quantity],["Total",r=>money(r.amount,r.currency)],["Status",r=><Badge>{r.status}</Badge>],["Actions",r=><div className="actions">{r.amount>0&&r.paid&&['confirmed','review'].includes(r.status)&&<Button secondary onClick={()=>setModal({type:'refund',record:r})}>Refund</Button>}{['pending','review'].includes(r.status)&&<button className="text-link" onClick={()=>act('status',{ref:r.ref},'payment-status')}>Check payment</button>}</div>]]}/></section></>;
 if(page==='attendees')content=<>{filterBar}<section className="panel"><div className="panel-heading"><h2>Guest list</h2><Button secondary onClick={()=>csv(filtered(tickets).map(({code,...t})=>t),'attendees')}><Download size={16}/>Export CSV</Button></div><Table rows={filtered(tickets)} columns={[["Attendee",r=>r.name],["Event",r=>r.title],["Ticket",r=>r.tier],["Status",r=><Badge>{r.status}</Badge>],["Admission",r=>r.checked_in?dateLabel(r.checked_in):'Not checked in'],["",r=>admin&&r.checked_in>0&&<button className="text-link" onClick={()=>act('check-in-undo',{ref:r.ref,version:r.version})}>Undo check-in</button>]]}/></section></>;
 if(page==='checkin')content=<CheckIn events={events} execute={execute} busy={busy}/>;
 if(page==='waitlist')content=<section className="panel"><Table rows={rows('waitlist')} columns={[["Name",r=>r.name],["Email",r=>r.email],["Event",r=>r.title],["Status",r=><Badge>{r.status}</Badge>],["",r=><Button secondary disabled={r.status==='notified'} onClick={()=>act('waitlist-notify',{ref:r.ref})}>Notify availability</Button>]]}/></section>;
 if(page==='staff')content=<section className="panel"><p>Assign active Cloudgate user IDs to specific events. Event staff can manage admission, but cannot access payments or settings.</p><Table rows={rows('staff')} columns={[["Name",r=>r.name],["User ID",r=>r.user_id],["Events",r=>r.events.map(id=>events.find(e=>e.ref===id)?.title||id).join(', ')],["Status",r=>r.active?'Active':'Disabled'],["",r=><button className="text-link" onClick={()=>setModal({type:'staff',record:r})}>Edit</button>]]}/></section>;
 if(page==='refunds')content=<section className="panel"><p>Full refunds are issued against verified Cloudgate payments. Tickets are blocked while a refund is pending and revoked when it succeeds.</p><Table rows={rows('refund')} columns={[["Booking",r=>r.order],["Amount",r=>money(r.amount,r.currency)],["Status",r=><Badge>{r.status}</Badge>],["Updated",r=>dateLabel(r.updated)]]}/></section>;
 if(page==='reports')content=<section className="panel"><div className="panel-heading"><h2>Event performance</h2><Button secondary onClick={()=>csv(events.map(e=>({event:e.title,currency:e.currency,confirmed:orders.filter(o=>o.event===e.ref&&o.status==='confirmed').reduce((n,o)=>n+o.quantity,0),revenue_minor:orders.filter(o=>o.event===e.ref&&o.status==='confirmed').reduce((n,o)=>n+o.amount,0),checked_in:tickets.filter(t=>t.event===e.ref&&t.checked_in).length})),'event-report')}>Export CSV</Button></div><Table rows={events} columns={[["Event",r=>r.title],["Confirmed tickets",r=>orders.filter(o=>o.event===r.ref&&o.status==='confirmed').reduce((n,o)=>n+o.quantity,0)],["Gross retained",r=>money(orders.filter(o=>o.event===r.ref&&o.status==='confirmed').reduce((n,o)=>n+o.amount,0),r.currency)],["Checked in",r=>tickets.filter(t=>t.event===r.ref&&t.checked_in).length]]}/><p className="muted">Confirmed bookings only. Refunded, pending and review bookings are excluded. Amounts are shown in each event’s currency, before payment-provider fees.</p></section>;
 if(page==='media')content=<MediaPanel data={data} go={go}/>;
 if(page==='email')content=<><SmtpSettings showTitle={false}/><section className="panel"><h2>Notification delivery</h2><Table rows={rows('message')} columns={[["Recipient",r=>r.recipient],["Subject",r=>r.subject],["Status",r=><Badge>{r.status}</Badge>],["Attempts",r=>r.attempts]]}/></section></>;
 if(page==='users')content=<UserManagement/>;if(page==='logs')content=<CloudgateWorkflowLogs showTitle={false}/>;if(page==='about')content=<CloudgateAbout showTitle={false}/>;if(page==='profile')content=<MyProfile account={profile} showTitle={false}/>;if(page==='settings')content=<EventSettings settings={settings} busy={busy} save={values=>act('settings',{values})}/>;
 if(!pages.includes(page))content=<Empty title="Section unavailable">Your account does not have access to this section.</Empty>;
 content=!signed||!staff?<>{header}<main className="login-card"><Ticket size={40}/><h1>Behind every great event.</h1><p>Sign in as an organiser or assigned event staff member.</p>{alerts}<Button onClick={()=>login('admin')}>Sign in to back office</Button></main></>:<div className="workspace"><BackOfficeNav pages={pages} labels={labels} icons={icons} page={page} go={go} identity={data.identity} role={data.role} logout={logout} drawer={drawer} setDrawer={setDrawer}/><div className="workspace-body"><header className="workspace-top"><div className="actions"><button className="icon-button menu-button" aria-label="Open navigation" onClick={()=>setDrawer(true)}><Menu/></button><span className="workspace-breadcrumb">Cloudgate Events <span>/</span> Organiser workspace</span></div><button className="icon-button" aria-label="Refresh workspace" onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={17}/></button></header><main className="workspace-main"><div className="page-heading"><div><span className="eyebrow">ORGANISER CONSOLE</span><h1>{labels[page]||'Workspace'}</h1></div>{admin&&['events','staff'].includes(page)&&<Button onClick={()=>setModal({type:page==='staff'?'staff':'event'})}><Plus size={16}/>Add {page==='staff'?'staff member':'event'}</Button>}</div>{alerts}{content}</main></div></div>;
 }else if(accountPath){content=<>{header}<main className="ticket-account"><span className="eyebrow">YOUR NEXT GOOD THING</span><h1>My tickets.</h1>{alerts}{!signed?<><p>Sign in to see your bookings and admission passes.</p><Button onClick={()=>login()}>Sign in</Button></>:<><div className="ticket-grid">{rows('ticket').map(t=><TicketPass ticket={t} key={t.ref}/>)}</div>{!rows('ticket').length&&<Empty title="Something to look forward to">Explore the events and find your next experience.</Empty>}<section className="panel"><h2>Bookings</h2><Table rows={rows('order')} columns={[["Event",r=><>{r.title}<small>{r.ref}</small></>],["Tickets",r=>r.quantity],["Total",r=>money(r.amount,r.currency)],["Status",r=><Badge>{r.status}</Badge>],["",r=>r.status==='pending'?<div className="actions"><Button onClick={()=>checkout(r)}>Continue payment</Button><button className="text-link" onClick={()=>act('status',{ref:r.ref},'payment-status')}>Check status</button><button className="text-link" onClick={()=>act('order-cancel',{ref:r.ref})}>Release reservation</button></div>:r.status==='review'?'The organiser is reviewing your booking.':null]]}/></section></>}</main>{footer}</>;
 }else{const event=catalog.events.find(e=>e.ref===new URLSearchParams(location.search).get('id')),filtered=catalog.events.filter(e=>(category==='All'||e.category===category)&&(e.title+' '+e.venue+' '+e.category).toLowerCase().includes(search.toLowerCase()));
 content=<>{header}{event?<main className="event-detail"><a href="/#discover" className="text-link">← Discover events</a><div className="event-detail-grid"><div><img className="event-detail-image" src={eventArtwork(event)} alt=""/><span className="eyebrow">{event.category}</span><h1>{event.title}</h1><p className="lead">{event.summary}</p><div className="event-facts"><span><CalendarDays size={18}/>{dateLabel(event.starts)}</span><span><MapPin size={18}/>{event.venue}</span></div><section><h2>About the experience</h2><p className="preserve">{event.description}</p><h3>Venue</h3><p>{event.address}</p><h3>Accessibility</h3><p>{event.accessibility||'Contact the organiser for accessibility information.'}</p><h3>Refund policy</h3><p>{event.refund_policy||'Contact the organiser for refund requests.'}</p><p>Organised by <strong>{event.organiser}</strong></p></section></div><aside className="booking-panel"><span className="eyebrow">SAVE YOUR SPOT</span><h2>You should be there.</h2>{alerts}{event.tiers.map(t=><div className="ticket-tier" key={t.ref}><div><h3>{t.name}</h3><p>{t.description}</p><small>{t.available} available</small></div><strong>{t.price?money(t.price,event.currency):'Free'}</strong><Button disabled={!t.available||t.sale_start>Date.now()/1000||t.sale_end<Date.now()/1000} onClick={()=>signed?setModal({type:'reserve',event,tier:t}):login()}>Choose tickets <ArrowRight size={15}/></Button></div>)}<button className="text-link" onClick={()=>signed?act('waitlist-join',{event:event.ref}):login()}>Join the waitlist</button><small className="checkout-note"><Ticket size={16}/>Your QR tickets live in your account.</small></aside></div></main>:<Storefront settings={settings} catalog={catalog} filtered={filtered} alerts={alerts} search={search} setSearch={setSearch} category={category} setCategory={setCategory}/>}{footer}</>;
 }
 const saveForm=(op,extra={})=>e=>{e.preventDefault();act(op,{...extra,...fields(e)});};
 return <>{preview&&<div className="preview-banner"><span>LOCAL PREVIEW · Payments and email are simulated</span><div>{['attendee','admin','staff'].map(r=><button key={r} onClick={()=>login(r)}>{r}</button>)}</div></div>}{content}{modal&&<Modal title={{event:'Event details',tier:'Ticket tier',staff:'Event staff',reserve:'Your tickets',refund:'Refund booking',cancel:'Cancel this event?',payment:'Preview payment'}[modal.type]} close={()=>!busy&&setModal(null)} wide={modal.type==='event'}>{alerts}
 {modal.type==='event'&&<EventForm record={modal.record} busy={busy} save={v=>act('event-save',v)}/>}
 {modal.type==='tier'&&<TierForm record={modal.record} event={modal.event} busy={busy} save={v=>act('tier-save',v)}/>}
 {modal.type==='staff'&&<form onSubmit={e=>{e.preventDefault();const f=fields(e);act('staff-save',{...modal.record,...f,events:new FormData(e.currentTarget).getAll('events'),active:f.active==='on'});}}><Field label="Name"><input name="name" required defaultValue={modal.record?.name}/></Field><Field label="Cloudgate user ID"><input name="user_id" required defaultValue={modal.record?.user_id}/></Field><fieldset><legend>Assigned events</legend>{events.map(e=><label className="checkbox" key={e.ref}><input type="checkbox" name="events" value={e.ref} defaultChecked={modal.record?.events.includes(e.ref)}/>{e.title}</label>)}</fieldset><label className="checkbox"><input name="active" type="checkbox" defaultChecked={modal.record?.active??true}/>Active</label><Button busy={busy}>Save staff member</Button></form>}
 {modal.type==='reserve'&&<Reservation event={modal.event} tier={modal.tier} name={data?.identity.name} busy={busy} save={async v=>{try{await execute('reserve',v);location.href='/account';}catch{}}}/>}
 {modal.type==='refund'&&<><p>Refund the full {money(modal.record.amount,modal.record.currency)} for {modal.record.title}? Admission tickets will be blocked while the refund is processed.</p><Button busy={busy} onClick={()=>act('refund',{ref:modal.record.ref,request_key:crypto.randomUUID()},'refund')}>Confirm full refund</Button></>}
 {modal.type==='cancel'&&<><p>Ticket sales will stop and existing tickets will be voided. Customers will receive a cancellation email. Paid bookings must then be refunded from Bookings.</p><Button busy={busy} onClick={()=>act('event-cancel',{ref:modal.record.ref,version:modal.record.version})}>Cancel event</Button></>}
 {modal.type==='payment'&&<><p>This is a local simulation. No money is charged.</p><Button busy={busy} onClick={()=>act('status',{ref:modal.record.ref,simulate:true},'payment-status')}>Simulate successful payment</Button></>}
 </Modal>}</>;
}

function EventForm({record:r={},busy,save}){const[image,setImage]=useState(r.image_url||'');return <form onSubmit={e=>{e.preventDefault();const v=fields(e);save({...r,...v,starts:Math.floor(new Date(v.starts).getTime()/1000),ends:Math.floor(new Date(v.ends).getTime()/1000),image_url:image});}}><div className="form-grid">{[['Title','title',r.title],['Category','category',r.category||'Music'],['Venue','venue',r.venue],['Organiser','organiser',r.organiser],['Starts (your local time)','starts',inputDate(r.starts||Date.now()/1000+86400),'datetime-local'],['Ends (your local time)','ends',inputDate(r.ends||Date.now()/1000+100800),'datetime-local'],['Total capacity','capacity',r.capacity||100,'number'],['Currency','currency',r.currency||'USD']].map(([label,name,value,type])=><Field label={label} key={name}><input required type={type||'text'} name={name} defaultValue={value} min={type==='number'?1:undefined}/></Field>)}</div><Field label="Address"><input name="address" defaultValue={r.address}/></Field>{[['Summary','summary'],['Description','description'],['Accessibility','accessibility'],['Refund policy','refund_policy']].map(([label,name])=><Field label={label} key={name}><textarea name={name} defaultValue={r[name]} rows={name==='description'?5:2}/></Field>)}<Asset label="Event artwork" value={image} change={setImage} path="events/events" aspect={1.5}/><Button busy={busy}>Save event</Button></form>;}
function TierForm({record:r={},event,busy,save}){return <form onSubmit={e=>{e.preventDefault();const v=fields(e);save({...r,...v,event:event.ref,price:Math.round(Number(v.price)*100),sale_start:Math.floor(new Date(v.sale_start).getTime()/1000),sale_end:Math.floor(new Date(v.sale_end).getTime()/1000),active:v.active==='on'});}}>{[['Name','name',r.name],['Price ('+event.currency+')','price',(r.price||0)/100,'number'],['Tier capacity','capacity',r.capacity||event.capacity,'number'],['Maximum per booking','max_per_order',r.max_per_order||6,'number'],['Sales open','sale_start',inputDate(r.sale_start||Date.now()/1000),'datetime-local'],['Sales close','sale_end',inputDate(r.sale_end||event.starts),'datetime-local']].map(([label,name,value,type])=><Field key={name} label={label}><input required type={type||'text'} step={name==='price'?'0.01':undefined} min={type==='number'?0:undefined} name={name} defaultValue={value}/></Field>)}<Field label="Description"><textarea name="description" defaultValue={r.description}/></Field><label className="checkbox"><input type="checkbox" name="active" defaultChecked={r.active??true}/>Sales active</label><Button busy={busy}>Save tier</Button></form>;}
function Reservation({event,tier,name,busy,save}){const[quantity,setQuantity]=useState(1),key=useRef(crypto.randomUUID());return <form onSubmit={e=>{e.preventDefault();save({tier:tier.ref,quantity,request_key:key.current,attendees:new FormData(e.currentTarget).getAll('attendee')});}}><p>{event.title} · {tier.name}</p><Field label="Number of tickets"><select value={quantity} onChange={e=>setQuantity(Number(e.target.value))}>{Array.from({length:Math.min(tier.max_per_order,tier.available)},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></Field>{Array.from({length:quantity},(_,i)=><Field label={'Attendee '+(i+1)} key={i}><input name="attendee" required maxLength={120} defaultValue={i===0?name:''}/></Field>)}<p><strong>Total: {money(tier.price*quantity,event.currency)}</strong></p><p className="muted">Paid reservations are held for 15 minutes before checkout. Your tickets are issued after payment confirmation.</p><Button busy={busy}>{tier.price?'Reserve tickets':'Confirm free tickets'}</Button></form>;}
function TicketPass({ticket:t}){const[qr,setQr]=useState('');useEffect(()=>{let live=true;import('qrcode').then(m=>(m.default||m).toDataURL(t.code,{width:240,margin:3,errorCorrectionLevel:'M'})).then(url=>live&&setQr(url));return()=>{live=false};},[t.code]);return <article className="admission-ticket"><div><span className="eyebrow">{t.tier}</span><h2>{t.title}</h2><p>{dateLabel(t.starts)}<br/>{t.venue}</p><strong>{t.name}</strong><p><Badge>{t.status}</Badge> {t.checked_in?'Checked in':''}</p></div><div className="ticket-code">{qr&&t.status==='valid'?<><img src={qr} alt="Admission QR code"/><a className="text-link" download={t.ref+'.png'} href={qr}><Download size={14}/>Save QR</a></>:<Ticket size={50}/>}<code>{t.ref}</code></div></article>;}
function CheckIn({events,execute,busy}){const[event,setEvent]=useState(events[0]?.ref||''),[code,setCode]=useState(''),[result,setResult]=useState(null),[camera,setCamera]=useState(false),[cameraError,setCameraError]=useState('');const video=useRef(null),submit=useRef(null);const scan=async value=>{setCamera(false);try{setResult(await execute('check-in',{event,code:value},undefined,false));setCode('');}catch{setResult(null);}};submit.current=scan;
 useEffect(()=>{if(!camera)return;let stopped=false,stream,frame;const canvas=document.createElement('canvas'),context=canvas.getContext('2d',{willReadFrequently:true});(async()=>{try{const jsQR=(await import('jsqr')).default;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});if(stopped){stream.getTracks().forEach(t=>t.stop());return;}video.current.srcObject=stream;await video.current.play();const tick=()=>{if(stopped)return;const v=video.current;if(v?.readyState>=2){canvas.width=v.videoWidth;canvas.height=v.videoHeight;context.drawImage(v,0,0);const image=context.getImageData(0,0,canvas.width,canvas.height),qr=jsQR(image.data,image.width,image.height);if(qr){submit.current(qr.data);return;}}frame=requestAnimationFrame(tick);};tick();}catch(e){if(!stopped){setCameraError('Camera unavailable. Allow camera access on HTTPS, or use the ticket code field.');setCamera(false);}}})();return()=>{stopped=true;cancelAnimationFrame(frame);stream?.getTracks().forEach(t=>t.stop());};},[camera]);
 return <section className="panel checkin-panel"><div className="checkin-symbol"><ScanLine size={40}/></div><h2>A warm welcome. One quick scan.</h2><p>Choose the event, then scan the guest’s ticket. Check-in requires an online connection.</p><Field label="Event"><select value={event} onChange={e=>{setEvent(e.target.value);setResult(null);setCamera(false);}}>{events.map(e=><option value={e.ref} key={e.ref}>{e.title}</option>)}</select></Field><Button secondary disabled={!event||busy} onClick={()=>{setCameraError('');setCamera(!camera);}}><Camera size={18}/>{camera?'Stop camera':'Open camera scanner'}</Button>{camera&&<video ref={video} playsInline muted className="scanner-video"/>}<ErrorBox error={cameraError}/><form onSubmit={e=>{e.preventDefault();scan(code.trim());}}><Field label="Ticket QR value or ticket reference"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Scan QR or enter TIC- reference" required autoComplete="off"/></Field><Button busy={busy} disabled={!event}>Check in guest <ArrowRight size={16}/></Button></form>{result&&<div className={'scan-result '+(result.ok?'accepted':'duplicate')} role="status"><strong>{result.ok?'Welcome in!':'Already checked in'}</strong><p>{result.name}</p>{result.duplicate&&<small>{dateLabel(result.checked_in)}</small>}</div>}</section>;
}
function EventSettings({settings,busy,save}){const[value,setValue]=useState({...settings,...brandSettings(settings)}),[tab,setTab]=useState('branding');useEffect(()=>setValue({...settings,...brandSettings(settings)}),[settings]);return <><div className="portal-tabs"><button className={tab==='branding'?'active':''} onClick={()=>setTab('branding')}>Theme & branding</button><button className={tab==='business'?'active':''} onClick={()=>setTab('business')}>Business & website</button></div><form onSubmit={e=>{e.preventDefault();save(value);}}><section className="panel">{tab==='branding'?<BrandingEditor value={value} change={(k,v)=>setValue(s=>({...s,[k]:v}))}/>:<>{[['Business name','name'],['Contact email','email'],['Phone','phone'],['Website URL','website_url'],['Hero headline','hero_title'],['Hero introduction','hero_subtitle'],['Footer description','description']].map(([l,k])=><Field label={l} key={k}><input value={value[k]||''} onChange={e=>setValue({...value,[k]:e.target.value})}/></Field>)}<p className="muted">Email uses Cloudgate by default. Configure an override in Email delivery only if needed.</p></>}</section><div className="sticky-save"><Button busy={busy}>Save settings</Button></div></form></>;}
createRoot(document.getElementById('root')).render(<App/>);
