PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS customer_accounts (Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id TEXT UNIQUE NOT NULL, name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', created INTEGER NOT NULL, updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS booking_accounts (Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, booking_ref TEXT UNIQUE NOT NULL REFERENCES bookings(reference), user_id TEXT NOT NULL, created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS booking_account_user ON booking_accounts(user_id);
CREATE TABLE IF NOT EXISTS settings (Id INTEGER PRIMARY KEY AUTOINCREMENT, key TEXT UNIQUE NOT NULL, value TEXT NOT NULL);
INSERT OR IGNORE INTO settings(key,value) VALUES('_revision','0');
CREATE TABLE IF NOT EXISTS write_guard (Id INTEGER PRIMARY KEY AUTOINCREMENT, expected TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS guard_revision BEFORE INSERT ON write_guard BEGIN
 SELECT RAISE(ABORT,'The calendar changed. Please retry your request.') WHERE NEW.expected<>(SELECT value FROM settings WHERE key='_revision');
END;
CREATE TABLE IF NOT EXISTS services (Id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'Wellness', description TEXT NOT NULL DEFAULT '', duration INTEGER NOT NULL CHECK(duration BETWEEN 5 AND 480), buffer INTEGER NOT NULL DEFAULT 10 CHECK(buffer BETWEEN 0 AND 120), price INTEGER NOT NULL CHECK(price>=0), deposit_percent INTEGER NOT NULL DEFAULT 100 CHECK(deposit_percent BETWEEN 1 AND 100), resource_type TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1, color TEXT NOT NULL DEFAULT '#b5c8b5', intake TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS staff (Id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, title TEXT NOT NULL DEFAULT '', bio TEXT NOT NULL DEFAULT '', color TEXT NOT NULL DEFAULT '#b5c8b5', service_ids TEXT NOT NULL DEFAULT '[]', hours TEXT NOT NULL DEFAULT '{}', active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS resources (Id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, type TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS blocks (Id INTEGER PRIMARY KEY AUTOINCREMENT, staff_id INTEGER REFERENCES staff(Id), resource_id INTEGER REFERENCES resources(Id), starts INTEGER NOT NULL, ends INTEGER NOT NULL CHECK(ends>starts), reason TEXT NOT NULL DEFAULT 'Unavailable');
CREATE TABLE IF NOT EXISTS customers (Id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT UNIQUE NOT NULL, name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', marketing INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS bookings (Id INTEGER PRIMARY KEY AUTOINCREMENT, reference TEXT UNIQUE NOT NULL, token_hash TEXT NOT NULL, request_key TEXT UNIQUE NOT NULL, customer_id INTEGER NOT NULL REFERENCES customers(Id), starts INTEGER NOT NULL, ends INTEGER NOT NULL, status TEXT NOT NULL CHECK(status IN ('held','confirmed','arrived','completed','cancelled','no_show','expired','payment_review')), expires INTEGER NOT NULL, total INTEGER NOT NULL, due INTEGER NOT NULL, paid INTEGER NOT NULL DEFAULT 0, refunded INTEGER NOT NULL DEFAULT 0, currency TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', intake TEXT NOT NULL DEFAULT '{}', payment_id TEXT, payment_url TEXT, created INTEGER NOT NULL, updated INTEGER NOT NULL, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS allocations (Id INTEGER PRIMARY KEY AUTOINCREMENT, booking_ref TEXT NOT NULL REFERENCES bookings(reference), service_id INTEGER NOT NULL REFERENCES services(Id), staff_id INTEGER NOT NULL REFERENCES staff(Id), resource_id INTEGER REFERENCES resources(Id), starts INTEGER NOT NULL, ends INTEGER NOT NULL CHECK(ends>starts), service_name TEXT NOT NULL, price INTEGER NOT NULL, duration INTEGER NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS allocations_staff_time ON allocations(staff_id,starts,ends,active);
CREATE INDEX IF NOT EXISTS allocations_resource_time ON allocations(resource_id,starts,ends,active);
CREATE TABLE IF NOT EXISTS payments (Id INTEGER PRIMARY KEY AUTOINCREMENT, booking_ref TEXT NOT NULL REFERENCES bookings(reference), external_id TEXT UNIQUE NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('payment','refund','cash')), amount INTEGER NOT NULL CHECK(amount>0), status TEXT NOT NULL, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS refund_requests (Id INTEGER PRIMARY KEY AUTOINCREMENT, request_key TEXT UNIQUE NOT NULL, booking_ref TEXT NOT NULL REFERENCES bookings(reference), amount INTEGER NOT NULL CHECK(amount>0), status TEXT NOT NULL DEFAULT 'pending', provider_id TEXT, created INTEGER NOT NULL);
DROP INDEX IF EXISTS one_pending_refund;
CREATE UNIQUE INDEX one_pending_refund ON refund_requests(booking_ref) WHERE status NOT IN ('succeeded','failed');
CREATE TABLE IF NOT EXISTS waitlist (Id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', service_id INTEGER NOT NULL REFERENCES services(Id), staff_id INTEGER REFERENCES staff(Id), preferred_date TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'waiting', created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS promos (Id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT UNIQUE NOT NULL, percent INTEGER NOT NULL CHECK(percent BETWEEN 1 AND 100), ends TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS messages (Id INTEGER PRIMARY KEY AUTOINCREMENT, booking_ref TEXT, recipient TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, due INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'queued', attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT NOT NULL DEFAULT '', dedupe TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS audit (Id INTEGER PRIMARY KEY AUTOINCREMENT, booking_ref TEXT, action TEXT NOT NULL, actor TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '', created INTEGER NOT NULL);
CREATE TRIGGER IF NOT EXISTS allocation_no_overlap BEFORE INSERT ON allocations WHEN NEW.active=1 BEGIN
 SELECT RAISE(ABORT,'That time was just booked. Please choose another slot.') WHERE EXISTS(SELECT 1 FROM allocations a JOIN bookings b ON b.reference=a.booking_ref WHERE a.active=1 AND (b.status<>'held' OR b.expires>CAST(strftime('%s','now') AS INTEGER)) AND a.starts<NEW.ends AND a.ends>NEW.starts AND (a.staff_id=NEW.staff_id OR (NEW.resource_id IS NOT NULL AND a.resource_id=NEW.resource_id)));
 SELECT RAISE(ABORT,'This time is blocked.') WHERE EXISTS(SELECT 1 FROM blocks b WHERE b.starts<NEW.ends AND b.ends>NEW.starts AND ((b.staff_id IS NULL AND b.resource_id IS NULL) OR b.staff_id=NEW.staff_id OR (NEW.resource_id IS NOT NULL AND b.resource_id=NEW.resource_id)));
END;
CREATE TRIGGER IF NOT EXISTS blocks_no_booking BEFORE INSERT ON blocks BEGIN
 SELECT RAISE(ABORT,'Move or cancel the affected appointments before blocking this time.') WHERE EXISTS(SELECT 1 FROM allocations a JOIN bookings b ON b.reference=a.booking_ref WHERE a.active=1 AND (b.status<>'held' OR b.expires>CAST(strftime('%s','now') AS INTEGER)) AND a.starts<NEW.ends AND a.ends>NEW.starts AND ((NEW.staff_id IS NULL AND NEW.resource_id IS NULL) OR a.staff_id=NEW.staff_id OR (NEW.resource_id IS NOT NULL AND a.resource_id=NEW.resource_id)));
END;

CREATE TABLE IF NOT EXISTS abandoned_booking_requests (Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, request_key TEXT NOT NULL UNIQUE, created INTEGER NOT NULL);
CREATE TRIGGER IF NOT EXISTS prevent_abandoned_booking BEFORE INSERT ON bookings WHEN EXISTS(SELECT 1 FROM abandoned_booking_requests WHERE request_key=NEW.request_key) BEGIN SELECT RAISE(ABORT,'This reservation request was released. Start a new booking.'); END;

INSERT OR IGNORE INTO settings(key,value) VALUES ('app_name',''),('app_short_name',''),('logo_url',''),('icon_url',''),('favicon_url',''),('logo_show_name','1'),('theme_primary','#294e3c'),('theme_accent','#7c896e'),('theme_background','#faf9f5');

INSERT OR IGNORE INTO settings(key,value) VALUES
('name','Still Studio'),('tagline','A little time. Entirely yours.'),('description','Thoughtful treatments, talented people, and a moment to slow down. Book your next massage, manicure, or reset.'),('currency','ZAR'),('timezone','Africa/Johannesburg'),('address','12 Kloof Street, Cape Town'),('phone','+27 21 555 0120'),('email','hello@example.com'),('lead_minutes','60'),('horizon_days','90'),('cancel_hours','24'),('hold_minutes','10'),('slot_minutes','15'),('website_url',''),('cancellation_policy','You can reschedule or cancel online up to 24 hours before your appointment. Eligible paid cancellations are reviewed for a refund by our team. Late cancellations: please contact the studio.'),('smtp_host',''),('smtp_port','587'),('smtp_user',''),('smtp_password',''),('smtp_from',''),('smtp_mode','starttls'),('reminder_hours','24');
