import React from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import '@cloudgatedevs/cloudgate-client-react/react/styles.css';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import '@fontsource/dm-sans/700.css';
import '@fontsource/instrument-serif/400.css';
import '@fontsource/instrument-serif/400-italic.css';
import './events/style.css';
import './events/branding.css';
import './events/events.css';
import './events/premium.css';
import './events/sdk.css';
import { App } from './App';
createRoot(document.getElementById('root')).render(<App />);
